package com.cxfdemo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2023-06-26T11:44:49.048+08:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "DeptInfoWSServiceImplService",
                  wsdlLocation = "http://10.123.10.213:8102/ws/autoDeptInfo?wsdl",
                  targetNamespace = "http://impl.service.shzx.com/")
public class DeptInfoWSServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.shzx.com/", "DeptInfoWSServiceImplService");
    public final static QName DeptInfoWSServiceImplPort = new QName("http://impl.service.shzx.com/", "DeptInfoWSServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.123.10.213:8102/ws/autoDeptInfo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeptInfoWSServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.123.10.213:8102/ws/autoDeptInfo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeptInfoWSServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeptInfoWSServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeptInfoWSServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DeptInfoWSServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DeptInfoWSServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DeptInfoWSServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DeptInfoWSServiceImpl
     */
    @WebEndpoint(name = "DeptInfoWSServiceImplPort")
    public DeptInfoWSServiceImpl getDeptInfoWSServiceImplPort() {
        return super.getPort(DeptInfoWSServiceImplPort, DeptInfoWSServiceImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeptInfoWSServiceImpl
     */
    @WebEndpoint(name = "DeptInfoWSServiceImplPort")
    public DeptInfoWSServiceImpl getDeptInfoWSServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DeptInfoWSServiceImplPort, DeptInfoWSServiceImpl.class, features);
    }

}
