server:
  port: 8102
spring:
  application:
    name: nx-boot-cxfway
  #遇到相同类名覆盖注册
  main:
    allow-bean-definition-overriding: true
# 集成cxf,默认：cxf.path=/services
cxf:
  path: /ws
#CXF服务常规发布开关，默认关闭
cxfenable: N
#CXF服务自动发布开关，默认关闭
autocxfenable: N