
package com.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserInfoWSServiceImpl", targetNamespace = "http://impl.service.shzx.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserInfoWSServiceImpl {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "testName", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.service.shzx.com/", className = "com.test.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.service.shzx.com/", className = "com.test.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "userInfo", targetNamespace = "")
    @RequestWrapper(localName = "getInfo", targetNamespace = "http://impl.service.shzx.com/", className = "com.test.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "http://impl.service.shzx.com/", className = "com.test.GetInfoResponse")
    public String getInfo();

}
